# run production locally

version: '3.8'

services:
  nmc-docker:
    container_name: nmc-docker
    # image: nemanjamitic/nemanjam.github.io:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        ARG_SITE_URL_AMD64: 'http://localhost:8080'
        # make separate script with localhost enabled
        ARG_PLAUSIBLE_SCRIPT_URL: 'https://plausible.arm1.nemanjamitic.com/js/script.js'
        # will trigger analytics
        ARG_PLAUSIBLE_DOMAIN: 'nemanjamitic.com'

    # platform: linux/arm64
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - '8080:8080'
    networks:
      - default

networks:
  default:
    name: nmc-default
